* Legal
Before you contribute, see LICENSE.

Copyright holders can be found in AUTHORS.

Contributing to OidaGroup upstreams requires special legal
steps. After submitting to us any changes, we will contact you with
steps that must happen prior to the changes being applied.

* Standards for C++

 - With the exception of mathmatical entities (vectors, matrixes,
   ect) - operators are not allowed
 - Avoid public variables of classes, if a class does have a public
   variable, its assumed to be thread-safe to access
 - Absolutely no function-argument references, only pointers
 - Composition is better than inheritance. Use inheritance wisely, if at all.
 - If you do intend to have a class inhertiable, document it. And make
   sure all methods have the =final= specificer that you do not intend
   to have overridden... open-ended polymorphism can lead to confusion
   more often than usefulness.
 - no templates.


** Naming conventions
 - cpp Classnames are CapCase
 - cpp fields are camelCase
 - (exported) c functions are snake_case
